[versions]
accompanistPermissions = "0.36.0"
activity = "1.9.2"
activityCompose = "1.10.0"
agp = "8.5.0"
androidJunitJupiter = "1.10.0.0"
androidxPaging = "3.3.4"
appcompat = "1.7.0"
assertj = "3.25.3"
constraintlayout = "2.1.4"
composeBom = "2025.01.01"
coreKtx = "1.13.1"
coroutine = "1.9.0"
coroutinesTest = "1.9.0-RC"
datastoreCoreAndroid = "1.1.1"
datastorePreferences = "1.1.1"
dotsindicator = "5.0"
espressoCore = "3.6.1"
firebaseBom = "33.3.0"
firebaseCrashlytics = "3.0.2"
firebaseMessaging = "24.0.1"
firebaseMessagingKtx = "24.0.1"
firebaseStorageKtx = "21.0.0"
fragmentKtx = "1.8.3"
fragmentTesting = "1.8.3"
glide = "4.16.0"
googleServices = "4.4.2"
hilt = "2.52"
hiltNavigationCompose = "1.2.0"
hiltWork = "1.2.0"
junitJupiter = "5.10.2"
junitVersion = "1.2.1"
jvm = "1.9.23"
kakaoShare = "2.20.3"
kotlin = "1.9.10"
ksp = "1.9.23-1.0.20"
ktlint = "12.1.1"
kakaoSdk = "2.20.3"
lifecycle = "2.2.0"
lifecycleViewmodel = "2.8.6"
loggingInterceptor = "4.12.0"
material = "1.12.0"
moshi = "1.15.1"
playServicesLocation = "21.3.0"
retrofit = "2.11.0"
room = "2.6.1"
splashScreen = "1.0.1"
timber = "5.0.1"
viewPager = "1.1.0"
workRuntimeKtx = "2.9.1"


[libraries]
# androidx
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltWork" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltWork" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-view-pager = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewPager" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashScreen" }
androidx-fragment-testing = { module = "androidx.fragment:fragment-testing", version.ref = "fragmentTesting" }
androidx-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "lifecycle" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodel" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastorePreferences" }
androidx-datastore-core-android = { group = "androidx.datastore", name = "datastore-core-android", version.ref = "datastoreCoreAndroid" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

# junit
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junitJupiter" }

# assertj
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }

# material
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# firebase
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging", version.ref = "firebaseMessaging" }
firebase-messaging-ktx = { group = "com.google.firebase", name = "firebase-messaging-ktx", version.ref = "firebaseMessagingKtx" }
firebase-storage-ktx = { group = "com.google.firebase", name = "firebase-storage-ktx", version.ref = "firebaseStorageKtx" }

# retrofit
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
retrofit-converter-scalars = { group = "com.squareup.retrofit2", name = "converter-scalars", version.ref = "retrofit" }

# moshi
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

# timber
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

# dotsindicator
dotsindicator = { group = "com.tbuonomo", name = "dotsindicator", version.ref = "dotsindicator" }

# loggig
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }

# play service
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }

# coroutines
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutine" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutinesTest" }

# kakao sdk
kakao-sdk-v2-user = { module = "com.kakao.sdk:v2-user", version.ref = "kakaoSdk" }

# glide
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }

# kakao share
kakao-share = { module = "com.kakao.sdk:v2-share", version.ref = "kakaoShare" }

# hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

# paging
androidx-paging = { group = "androidx.paging", name = "paging-runtime", version.ref = "androidxPaging" }

# compose
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

# permission
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jvm" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServices" }
android-junit-jupiter = { id = "de.mannodermaus.android-junit5", version.ref = "androidJunitJupiter" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }
