spring:
  data:
    redis:
      host: ody-redis-001.ody-redis.vd1e5e.apn2.cache.amazonaws.com
      ssl:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(EbLprih9CBRFwayAtzOuQgmLIi1yhY0XKl7h7Ol8ioyJdMtwwHN6caPxplZ7UXUCSCTYfUZ9MgMZ+BLdP2rka97Bx/vmtXo5ysJzdYLLzywI0XTylX4o5N8RQlk1Tx2s7vRI2khoJZ5p6zCdIBaJWw==)
    username: ENC(Wd8cwBhFGAJp/RMvZzrOzw==)
    password: ENC(X2Gk3hAja3lLSUyJLewcdVWZh3hTJDiJ)
  flyway:
    baseline-version: 2

log:
  file:
    path: /ody-dev-logs
